# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
